// ignore_for_file: non_constant_identifier_names

class Autogenerated {
  bool? status;
  String? message;
  List<Data>? data;

  Autogenerated({this.status, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int? id;
  String? matkhau;
  String? email;
  String? hoten;
  String? nguoi_dong_tien;
  String? thoi_gian;
  int? thoi_gian_CT;
  int? so_tran_tham_gia;
  String? ngay_bat_dau;
  String? ngay_ket_thuc;
  int? so_luong_doi_bong;
  String? ho_ten;
  String? sdt;
  int? so_the_vang;
  int? soTienQuy;
  String? avatar;
  String? ngaydangky;
  String? ten_cau_thu;
  String? tensp;
  String? ten_hinh_thuc;
  String? noi_dung;
  String? trang_thai;
  int? so_tran_toi_thieu;
  int? so_doi_toi_thieu;
  int? rank;
  int? khoa;
  String? logo;
  int? so_ao;
  String? vi_tri;
  int? id_tai_khoan;
  int? sl_thanh_vien;
  int? nguoiQuanLyId;
  String? tenDoiBong;
  int? soDiem;
  String? gioithieu;
  int? soTranDau;
  int? soTranThang;
  int? soTranHoa;
  int? doi_bong_id;
  int? soTranThua;
  int? soBanThang;
  String? vai_tro;
  int? trangThaiDangKy;
  String? ban_to_chuc;
  int? tong_so_tran;
  String? danh_muc;
  int? tong_ban_thang;
  int? so_the_do;
  int? tong_ban_thua;
  int? gia;
  String? tieu_de;
  int? hinh_thuc_dau_id;
  String? ten_giai_dau;
  int? giaiDauId;
  int? tran_dau_id;
  int? thang;
  int? id_cau_thu;
  int? tong_diem;
  String? loaiTaiKhoan;
  String? lop;
  int? thua;
  String? loai_thong_tin;
  int? hoa;
  int? so_bang_dau;
  int? so_doi_vao_vong_trong;
  int? loai_san;
  int? so_vong_dau;
  String? san_dau;
  int? so_tran_da_dau;
  int? the_phat;
  int? phat_den;
  String? createdAt;
  String? updatedAt;

  Data(
      {this.id,
      this.ngay_bat_dau,
      this.ngay_ket_thuc,
      this.tran_dau_id,
      this.matkhau,
      this.vai_tro,
      this.email,
      this.so_the_do,
      this.id_cau_thu,
      this.so_ao,
      this.so_tran_tham_gia,
      this.giaiDauId,
      this.thang,
      this.so_doi_vao_vong_trong,
      this.so_bang_dau,
      this.loai_san,
      this.id_tai_khoan,
      this.thoi_gian_CT,
      this.avatar,
      this.so_the_vang,
      this.soTienQuy,
      this.nguoi_dong_tien,
      this.doi_bong_id,
      this.ten_cau_thu,
      this.thoi_gian,
      this.so_vong_dau,
      this.danh_muc,
      this.tieu_de,
      this.tong_ban_thua,
      this.ten_giai_dau,
      this.so_tran_da_dau,
      this.rank,
      this.ban_to_chuc,
      this.ngaydangky,
      this.tong_diem,
      this.ho_ten,
      this.so_luong_doi_bong,
      this.san_dau,
      this.hinh_thuc_dau_id,
      this.thua,
      this.hoten,
      this.vi_tri,
      this.ten_hinh_thuc,
      this.hoa,
      this.sdt,
     this.trangThaiDangKy,
      this.trang_thai,
      this.noi_dung,
      this.tong_ban_thang,
      this.so_tran_toi_thieu,
      this.so_doi_toi_thieu,
      this.tensp,
      this.nguoiQuanLyId,
      this.tenDoiBong,
      this.soDiem,
      this.gioithieu,
      this.soTranDau,
      this.tong_so_tran,
      this.soTranThang,
      this.soTranHoa,
      
      this.soTranThua,
      this.soBanThang,
      this.gia,
      this.loaiTaiKhoan,
      this.khoa,
      this.sl_thanh_vien,
      this.the_phat,
      this.phat_den,
      this.lop,
      this.createdAt,
      this.updatedAt});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    matkhau = json['matkhau'];
    ten_cau_thu = json['ten_cau_thu'];
    email = json['email'];
    vai_tro = json['vai_tro'];
    tieu_de=json['tieu_de'];
    thoi_gian_CT = json['thoi_gian_CT'];
    thoi_gian = json['thoi_gian'];
    tran_dau_id = json['tran_dau_id'];
    doi_bong_id = json['doi_bong_id'];
    so_tran_tham_gia = json['so_tran_tham_gia'];
    nguoi_dong_tien = json['nguoi_dong_tien'];
    danh_muc = json['danh_muc'];
    avatar = json['avatar'];
    so_the_vang = json['so_the_vang'];
    so_tran_da_dau = json['so_tran_da_dau'];
    san_dau = json['san_dau'];
    so_the_do = json['so_the_do'];
    soTienQuy=json['so_tien_quy'];
    giaiDauId = json['giai_dau_id'];
    so_ao = json['so_ao'];
    tong_ban_thua = json['tong_ban_thua'];
    id_cau_thu = json['id_cau_thu'];
    trangThaiDangKy=json['trang_thai_dang_ky'];
    ngaydangky=json['ngay_dang_ky'];
    ngay_bat_dau = json['ngay_bat_dau'];
    ngay_ket_thuc = json['ngay_ket_thuc'];
    so_luong_doi_bong = json['so_luong_doi_bong'];
    ten_giai_dau = json['ten_giai_dau'];
    hoa = json['hoa'];
    id_tai_khoan=json['id_tai_khoan'];
    so_vong_dau = json['so_vong_dau'];
    ban_to_chuc = json['ban_to_chuc'];
    logo = json['logo'];
    hinh_thuc_dau_id = json['hinh_thuc_dau_id'];
    rank = json['rank'];
    thua = json['thua'];
    thang = json['thang'];
    tong_ban_thang = json['tong_ban_thang'];
    tong_diem = json['tong_diem'];
    hoten = json['hoten'];
    vi_tri = json['vi_tri'];
    ho_ten = json['ho_ten'];
    tong_so_tran = json['tong_so_tran'];
    trang_thai = json['trang_thai'];
    ten_hinh_thuc = json['ten_hinh_thuc'];
    tensp = json['tensp'];
    noi_dung = json['noi_dung'];
    so_tran_toi_thieu = json['so_tran_toi_thieu'];
    so_doi_toi_thieu = json['so_doi_toi_thieu'];
   
    nguoiQuanLyId = json['nguoi_quan_ly_id'];
    tenDoiBong = json['ten_doi_bong'];
    soDiem = json['so_diem'];
    gioithieu = json['gioithieu'];
    the_phat = json['the_phat'];
    phat_den = json['phat_den'];
    soTranDau = json['so_tran_dau'];
    soTranHoa = json['so_tran_hoa'];
    soTranThang = json['so_tran_thang'];
    soTranThua = json['so_tran_thua'];
    soBanThang = json['so_ban_thang'];
    gia = json['gia'];
    khoa = json['khoa'];
    sl_thanh_vien = json['sl_thanh_vien'];
    sdt = json['sdt'];
    loaiTaiKhoan = json['loai_tai_khoan'];
    lop = json['lop'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    loai_san = json['loai_san'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['so_tran_da_dau'] = this.so_tran_da_dau;
    data['matkhau'] = this.matkhau;
    data['so_the_do']= this.so_the_do;
    data['thoi_gian_CT']=this.thoi_gian_CT;
    data['id_cau_thu']=this.id_cau_thu;
    data['giai_dau_id']=this.giaiDauId;
    data['nguoi_dong_tien']=this.nguoi_dong_tien;
    data['ten_cau_thu'] = this.ten_cau_thu;
    data['so_ao']=this.so_ao;
    data['tran_dau_id']=this.tran_dau_id;
    data['so_tien_quy']=this.soTienQuy;
    data['avatar']=this.avatar;
    data['id_tai_khoan']=this.id_tai_khoan;
    data['vai_tro']=this.vai_tro;
    data['tieu_de']=this.tieu_de;
    data['so_the_vang']=this.so_the_vang;
    data['thoi_gian']=this.thoi_gian;
    data['tong_ban_thang']=this.tong_ban_thang;
    data['ngay_bat_dau'] = this.ngay_bat_dau;
    data['ngay_ket_thuc'] = this.ngay_ket_thuc;
    data['email'] = this.email;
    data['ngay_dang_ky']=this.ngaydangky;
    data['tong_ban_thua']=this.tong_ban_thua;
    data['so_luong_doi_bong'] = this.so_luong_doi_bong;
    data['san_dau'] = this.san_dau;
    data['hoa'] = this.hoa;
    data['danh_muc']=this.danh_muc;
    data['so_tran_hoa']=this.soTranHoa;
    data['so_vong_dau'] = this.so_vong_dau;
    data['ten_giai_dau'] = this.ten_giai_dau;
    data['ho_ten'] = this.ho_ten;
    data['ban_to_chuc'] = this.ban_to_chuc;
    data['thua'] = this.thua;
    data['hinh_thuc_dau_id'] = this.hinh_thuc_dau_id;
    data['logo'] = this.logo;
    data['doi_bong_id'] = this.doi_bong_id;
    data['tong_diem'] = this.tong_diem;
    data['tong_so_tran'] = this.tong_so_tran;
    data['tensp'] = this.tensp;
    data['rank'] = this.rank;
    data['noi_dung'] = this.noi_dung;
    data['thang'] = this.thang;
    data['vi_tri'] = this.vi_tri;
    data['so_tran_toi_thieu'] = this.so_tran_toi_thieu;
    data['so_doi_toi_thieu'] = this.so_doi_toi_thieu;
    data['ten_hinh_thuc'] = this.ten_hinh_thuc;
    data['trang_thai'] = this.trang_thai;
    data['gia'] = this.gia;
    data['gioithieu'] = this.gioithieu;
    data['hoten'] = this.hoten;
    data['sdt'] = this.sdt;
    data['loai_tai_khoan'] = this.loaiTaiKhoan;
    data['lop'] = this.lop;
    data['nguoi_quan_ly_id'] = this.nguoiQuanLyId;
    data['ten_doi_bong'] = this.tenDoiBong;
    data['khoa'] = this.khoa;
    data['sl_thanh_vien'] = this.sl_thanh_vien;
    data['so_diem'] = this.soDiem;
    data['so_tran_dau'] = this.soTranDau;
    data['so_tran_thang'] = this.soTranThang;
    data['so_tran_thua'] = this.soTranThua;
    data['so_ban_thang'] = this.soBanThang;
    data['the_phat'] = this.the_phat;
    data['phat_den'] = this.phat_den;
    data['trang_thai_dang_ky'] = this.trangThaiDangKy;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['loai_san'] = this.loai_san;
    return data;
  }
}
